services:
  - type: web
    name: vallionis-ai-finance
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --timeout 1000 app:app"
    build:
      pythonVersion: 3.12.3
