"""Initial migration

Revision ID: 737a514bce99
Revises: 
Create Date: 2025-07-15 21:44:11.917207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '737a514bce99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('premium', sa.Boolean(), nullable=True),
    sa.Column('subscription_expires', sa.DateTime(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=50), nullable=True),
    sa.Column('subscription_type', sa.String(length=20), nullable=True),
    sa.Column('subscription_status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('current_user_preferences',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('investing_style', sa.String(length=20), nullable=True),
    sa.Column('time_horizon', sa.Integer(), nullable=True),
    sa.Column('risk_tolerance', sa.String(length=20), nullable=True),
    sa.Column('sector_focus', sa.String(length=20), nullable=True),
    sa.Column('dividend_preference', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_preference_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('investing_style', sa.String(length=20), nullable=True),
    sa.Column('time_horizon', sa.Integer(), nullable=True),
    sa.Column('risk_tolerance', sa.String(length=20), nullable=True),
    sa.Column('sector_focus', sa.String(length=20), nullable=True),
    sa.Column('dividend_preference', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preference_history')
    op.drop_table('current_user_preferences')
    op.drop_table('users')
    # ### end Alembic commands ###
